const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const SRC_DIR = path.join(ROOT, "content-src");
const OUT_FILE = path.join(ROOT, "content.js");

const files = fs.readdirSync(SRC_DIR)
  .filter((name) => name.endsWith(".js"))
  .sort();

const body = files
  .map((name) => fs.readFileSync(path.join(SRC_DIR, name), "utf8").trimEnd())
  .join("\n\n");

const output = `// AFlodit Pet Copilot content script v0.6.5\n// Generated by build-content.js. Edit content-src/*.js, then run: node build-content.js\n\n(() => {\n  "use strict";\n\n${body}\n})();\n`;

fs.writeFileSync(OUT_FILE, output, "utf8");
console.log(`Built ${path.relative(ROOT, OUT_FILE)} from ${files.length} source files.`);
