const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const SRC_DIR = path.join(ROOT, "content-src");
const OUT_FILE = path.join(ROOT, "content.js");

const files = [
  "commands/commandSchema.js",
  "commands/builtinCommands.js",
  "commands/commandParser.js",
  "commands/commandRegistry.js",
  "01-core.js",
  "02-dom.js",
  "03-extractor.js",
  "04-face.js",
  "05-layout.js",
  "06-actions.js",
  "07-app.js",
  "08-pomodoro.js"
];

for (const file of files) {
  const fullPath = path.join(SRC_DIR, file);
  if (!fs.existsSync(fullPath)) {
    throw new Error(`Missing content source file: ${file}`);
  }
}

const body = files
  .map((name) => fs.readFileSync(path.join(SRC_DIR, name), "utf8").trimEnd())
  .join("\n\n");

const output = `// AFlodit Pet Copilot content script v0.8.0\n// Generated by build-content.js. Edit explicit sources in build-content.js, then run: node build-content.js\n\n(() => {\n  "use strict";\n\n${body}\n})();\n`;

fs.writeFileSync(OUT_FILE, output, "utf8");
console.log(`Built ${path.relative(ROOT, OUT_FILE)} from ${files.length} source files.`);
