// AFlodit Pet Copilot content script v0.6.3
// Generated by build-content.js. Edit content-src/*.js, then run: node build-content.js

(() => {
  "use strict";

const GLOBAL_KEY = "__AFLODIT_PET_COPILOT__";
  window[GLOBAL_KEY]?.destroy?.();
  document.getElementById("aflodit-pet-root")?.remove();
// =========================
  // 1. 常量 / 配置
  // =========================
  const ACTION = Object.freeze({
    CHAT: "chat",
    EXPLAIN: "explain_selection",
    SUMMARY: "summarize_page",
    TRANSLATE: "translate"
  });

  const UI = Object.freeze({ IDLE: "idle", MENU: "menu", PANEL: "panel" });

  const MODE = Object.freeze({
    NORMAL: "normal",
    READING: "reading"
  });

  const ACTIVITY = Object.freeze({
    IDLE: "idle",
    OBSERVING: "observing",
    TRACKING_MOUSE: "tracking_mouse",
    THINKING: "thinking",
    RESPONDING: "responding"
  });

  const CONFIG = Object.freeze({
    version: "0.6.3",
    backendUrl: "http://127.0.0.1:3001/api/pet",
    streamUrl: "http://127.0.0.1:3001/api/pet-stream",
    streamEnabled: true,
    localClientToken: "aflodit-pet-local-dev",
    debug: false,
    limits: Object.freeze({
      action: 32,
      userText: 1000,
      selectedText: 4000,
      pageTitle: 256,
      pageUrl: 2048,
      pageText: 6000,
      characterState: 64,
      pagePreview: 1000
    }),
    reading: Object.freeze({
      mouseRange: 260,
      mouseHoldMs: 900,
      glanceDelay: Object.freeze({ min: 1200, max: 2400 })
    }),
    face: Object.freeze({
      menuLookDelay: Object.freeze({ min: 700, max: 1300 }),
      replyPeekStartMs: 10000,
      replyPeekHoldMs: Object.freeze({ min: 900, max: 1400 }),
      replyPeekGapMs: Object.freeze({ min: 3500, max: 7000 }),
      ideaBulbHoldMs: 1180,
      eyeMoveRange: 6,
      mouthMoveRange: 3,
      vectorNormX: 120,
      vectorNormY: 100
    }),
    drag: Object.freeze({
      avatarSize: 64,
      initialOffset: 24,
      viewportMargin: 12,
      snapDistance: 78,
      dragThreshold: 4,
      panelGap: 20,
      helpGap: 10,
      menuWidth: 240,
      menuHeight: 190,
      floatingWidth: 360,
      helpHeight: 132
    })
  });

  const ACTION_CONFIG = Object.freeze({
    [ACTION.CHAT]: Object.freeze({
      label: "Chat",
      refreshable: false,
      needsSelection: false,
      needsUserText: true,
      sendsPageText: false,
      context: "none",
      idle: "马上开始对话吧。",
      loading: "正在执行：Chat",
      empty: "请输入要发送的消息。"
    }),
    [ACTION.EXPLAIN]: Object.freeze({
      label: "Explain",
      refreshable: true,
      needsSelection: true,
      needsUserText: false,
      sendsPageText: false,
      context: "selection",
      contextTitle: "选中文本",
      idle: "正在准备解释选中文本。",
      loading: "正在执行：Explain",
      empty: "请先在网页中选中一段文本。解释和翻译都依赖 selected_text。"
    }),
    [ACTION.SUMMARY]: Object.freeze({
      label: "Summarize",
      refreshable: true,
      needsSelection: false,
      needsUserText: false,
      sendsPageText: true,
      context: "page",
      contextTitle: "当前页面",
      idle: "正在准备总结当前页面。",
      loading: "正在执行：Summarize",
      empty: "当前无法读取页面内容，暂时不能总结这个页面。"
    }),
    [ACTION.TRANSLATE]: Object.freeze({
      label: "Translate",
      refreshable: true,
      needsSelection: true,
      needsUserText: false,
      sendsPageText: false,
      context: "selection",
      contextTitle: "选中文本",
      idle: "正在准备翻译选中文本。",
      loading: "正在执行：Translate",
      empty: "请先在网页中选中一段文本。解释和翻译都依赖 selected_text。"
    })
  });

  const FACE_PARTS = Object.freeze({
    neutral: Object.freeze({ left: "●", mouth: "ᴗ", right: "●", mark: "" }),
    happy: Object.freeze({ left: "●", mouth: "ᴗ", right: "●", mark: "" }),
    // 思考中保留原眼型和原眼位；嘴巴由 FaceController 渲染为固定宽度的流动波浪线。
    thinking: Object.freeze({ left: "●", mouth: "ᴗ", right: "●", mark: "" }),
    // 返回成功瞬间使用：配合灯泡特效，表达“想到了”。
    idea: Object.freeze({ left: "●", mouth: "o", right: "●", mark: "!" }),
    confused: Object.freeze({ left: "・", mouth: "_", right: "・", mark: "?" }),
    error: Object.freeze({ left: "×", mouth: "_", right: "×", mark: "" })
  });

  const READABLE_SELECTORS = Object.freeze([
    "article",
    "main",
    "[role='main']",
    "#mw-content-text .mw-parser-output",
    ".mw-parser-output",
    "article.markdown-body",
    "section",
    "div"
  ]);

  const READABLE_SAFE_REMOVE_SELECTORS = Object.freeze([
    "#aflodit-pet-root",
    "script",
    "style",
    "noscript",
    "template"
  ]);

  // 以右下角默认状态为基准：三气泡在头像左上侧，距离接近初版。
  // 其它象限通过 dx / dy 镜像得到，不再单独维护四套 CSS。
  const MENU_BUTTON_OFFSETS = Object.freeze([
    { key: ACTION.TRANSLATE, dx: -12, dy: -84 },
    { key: ACTION.EXPLAIN, dx: -104, dy: -36 },
    { key: ACTION.SUMMARY, dx: -118, dy: 18 }
  ]);
// =========================
  // 2. 运行态
  // =========================
  const state = {
    ui: UI.IDLE,
    mode: MODE.NORMAL,
    activity: ACTIVITY.IDLE,
    action: ACTION.CHAT,
    selectedText: "",
    running: false,
    requestId: 0,
    lookTimer: null,
    replyPeekTimer: null,
    readingTimer: null,
    ideaTimer: null,
    lastMouseAt: 0,
    position: { x: 0, y: 0, snapEdge: "free" },
    layout: {
      menuVariant: "br",
      panelPlacement: "top"
    },
    drag: {
      active: false,
      pointerId: null,
      startX: 0,
      startY: 0,
      originX: 0,
      originY: 0,
      moved: false,
      suppressClick: false
    }
  };

  const dom = {};
  const cleanups = [];
// =========================
  // 3. 工具函数
  // =========================
  const log = (...args) => CONFIG.debug && console.log("[AFlodit Pet]", ...args);
  const text = (value) => String(value ?? "").trim();
  const limit = (value, max) => text(value).slice(0, max);
  const actionConfig = (action) => ACTION_CONFIG[action] || ACTION_CONFIG[ACTION.CHAT];
  const clamp = (value, min, max) => Math.max(min, Math.min(max, value));
  const randomBetween = (min, max) => min + Math.random() * (max - min);

  function on(target, type, handler, options) {
    target.addEventListener(type, handler, options);
    cleanups.push(() => target.removeEventListener(type, handler, options));
  }
// =========================
  // 9. 公共状态设置
  // =========================
  function setMode(mode = MODE.NORMAL) {
    const safeMode = Object.values(MODE).includes(mode) ? mode : MODE.NORMAL;
    state.mode = safeMode;
    if (dom.root) {
      dom.root.dataset.mode = safeMode;
      dom.root.classList.toggle("pet-mode-reading", safeMode === MODE.READING);
    }
  }

  function setActivity(activity = ACTIVITY.IDLE) {
    const safeActivity = Object.values(ACTIVITY).includes(activity) ? activity : ACTIVITY.IDLE;
    state.activity = safeActivity;
    if (dom.root) dom.root.dataset.activity = safeActivity;
  }

  function setBubbleType(type = "normal") {
    dom.panel.classList.remove("bubble-type-normal", "bubble-type-info", "bubble-type-warning", "bubble-type-error");
    dom.panel.classList.add(`bubble-type-${type || "normal"}`);
  }

  function setMeta(emotion, motion) {
    dom.meta.textContent = `emotion: ${emotion} | motion: ${motion}`;
  }

  function setRunning(running) {
    state.running = running;
    dom.quickButtons.forEach((button) => { button.disabled = running; });
    dom.chatSend.disabled = running;
    dom.chatInput.disabled = running;
    dom.refresh.disabled = running;
  }

// =========================
  // 5. DOM / 模板
  // =========================
  function renderTemplate() {
    return `
      <div id="aflodit-pet">
        <div id="aflodit-pet-menu" class="pet-quick-menu hidden">
          <button class="pet-quick-action" data-action="${ACTION.TRANSLATE}">translate</button>
          <button class="pet-quick-action" data-action="${ACTION.EXPLAIN}">explain</button>
          <button class="pet-quick-action" data-action="${ACTION.SUMMARY}">summarize</button>
        </div>

        <div id="aflodit-pet-help" class="pet-floating-help hidden">
          <div class="pet-help-title">快捷说明</div>
          <div class="pet-help-line"><b>Enter</b>：发送 Chat</div>
          <div class="pet-help-line"><b>Esc</b>：关闭面板</div>
          <div class="pet-help-line"><b>@选区</b>：引用当前选中文本</div>
          <div class="pet-help-line"><b>@页面</b>：引用当前页面正文</div>
          <div class="pet-help-line"><b>@陪读</b>：进入陪读模式</div>
          <div class="pet-help-line pet-help-muted">例：@选区 解释这段话</div>
          <div class="pet-help-line pet-help-muted">例：@页面 这页主要讲什么</div>
        </div>

        <div id="aflodit-pet-panel" class="hidden bubble-type-normal">
          <div class="pet-title-row">
            <div class="pet-title">AFlodit Pet Copilot <span class="pet-version">${CONFIG.version}</span></div>
            <div class="pet-title-actions">
              <button id="aflodit-pet-help-button" class="pet-help-button" title="快捷说明">?</button>
              <div id="aflodit-pet-mode" class="pet-mode-tag">Chat</div>
            </div>
          </div>

          <div id="aflodit-pet-status" class="pet-status">请选择一种使用方式。</div>

          <div id="aflodit-pet-context-block">
            <div id="aflodit-pet-context-title" class="pet-section-title">选中文本</div>
            <div id="aflodit-pet-selected" class="pet-text pet-selected-text">暂无选中文本。</div>
          </div>

          <div class="pet-reply-title-row">
            <div class="pet-section-title pet-reply-title">助手回复</div>
            <button id="aflodit-pet-refresh-action" class="pet-refresh-button hidden" title="重新执行当前动作">↻</button>
          </div>
          <div id="aflodit-pet-reply" class="pet-text pet-reply-text">暂无回复。</div>

          <div id="aflodit-pet-meta" class="pet-meta">emotion: neutral | motion: idle</div>

          <div id="aflodit-pet-chat-row" class="pet-chat-row hidden">
            <input id="aflodit-pet-chat-input" class="pet-chat-input" placeholder="马上开始对话吧" />
            <button id="aflodit-pet-chat-send" class="pet-chat-button">发送</button>
          </div>
        </div>

        <div id="aflodit-pet-avatar" title="AFlodit Pet Copilot">
          <span id="aflodit-pet-idea-bulb" class="pet-idea-bulb hidden" aria-hidden="true">
            <span class="pet-idea-bulb-glow"></span>
            <span class="pet-idea-bulb-ray pet-idea-bulb-ray-1"></span>
            <span class="pet-idea-bulb-ray pet-idea-bulb-ray-2"></span>
            <span class="pet-idea-bulb-ray pet-idea-bulb-ray-3"></span>
            <span class="pet-idea-bulb-spark pet-idea-bulb-spark-1"></span>
            <span class="pet-idea-bulb-spark pet-idea-bulb-spark-2"></span>
            <span class="pet-idea-bulb-spark pet-idea-bulb-spark-3"></span>
            <span class="pet-idea-bulb-glass"></span>
            <span class="pet-idea-bulb-core"></span>
            <span class="pet-idea-bulb-base"></span>
          </span>
          <span id="aflodit-pet-face" class="pet-face-core face-emotion-neutral" aria-hidden="true">
            <span id="aflodit-pet-eye-left" class="pet-face-part pet-eye pet-eye-left">●</span><span id="aflodit-pet-mouth" class="pet-face-part pet-mouth">ᴗ</span><span id="aflodit-pet-eye-right" class="pet-face-part pet-eye pet-eye-right">●</span><span id="aflodit-pet-face-mark" class="pet-face-part pet-face-mark"></span>
          </span>
        </div>
      </div>
    `;
  }

  function injectIdeaMotionStyle() {
    if (document.getElementById("aflodit-pet-idea-motion-style")) return;

    const style = document.createElement("style");
    style.id = "aflodit-pet-idea-motion-style";
    style.textContent = `
      #aflodit-pet-avatar {
        position: relative;
        overflow: visible !important;
      }

      .pet-idea-bulb.hidden {
        display: none !important;
      }

      .pet-idea-bulb {
        position: absolute;
        left: -21px;
        top: -42px;
        width: 46px;
        height: 56px;
        pointer-events: none;
        z-index: 7;
        transform-origin: 54% 88%;
        animation: af-pet-idea-bulb-dance 1180ms cubic-bezier(.18,.85,.28,1.25) both;
      }

      .pet-idea-bulb-glow {
        position: absolute;
        left: 3px;
        top: -1px;
        width: 38px;
        height: 38px;
        border-radius: 50%;
        background: radial-gradient(circle, rgba(255,236,128,.72) 0%, rgba(255,236,128,.28) 42%, rgba(255,236,128,0) 72%);
        filter: blur(1px);
        animation: af-pet-idea-glow 1180ms ease-out both;
      }

      .pet-idea-bulb-glass {
        position: absolute;
        left: 8px;
        top: 4px;
        width: 27px;
        height: 30px;
        border: 3px solid #222;
        border-radius: 50% 50% 46% 46%;
        background: #fff2a0;
        box-shadow:
          0 0 0 2px rgba(255,255,255,.28) inset,
          0 0 12px rgba(255,220,80,.58);
      }

      .pet-idea-bulb-glass::after {
        content: "";
        position: absolute;
        left: 6px;
        top: 5px;
        width: 7px;
        height: 7px;
        border-radius: 50%;
        background: rgba(255,255,255,.86);
      }

      .pet-idea-bulb-core {
        position: absolute;
        left: 18px;
        top: 19px;
        width: 8px;
        height: 7px;
        border: 2px solid #222;
        border-top: 0;
        border-radius: 0 0 8px 8px;
        opacity: .86;
      }

      .pet-idea-bulb-base {
        position: absolute;
        left: 14px;
        top: 32px;
        width: 16px;
        height: 14px;
        border: 3px solid #222;
        border-top: 0;
        border-radius: 3px 3px 8px 8px;
        background: #f7f7f7;
      }

      .pet-idea-bulb-base::before,
      .pet-idea-bulb-base::after {
        content: "";
        position: absolute;
        left: 2px;
        width: 12px;
        height: 2px;
        border-radius: 999px;
        background: #222;
      }

      .pet-idea-bulb-base::before { top: 4px; }
      .pet-idea-bulb-base::after { top: 9px; }

      .pet-idea-bulb-ray {
        position: absolute;
        width: 12px;
        height: 3px;
        border-radius: 999px;
        background: #222;
        opacity: 0;
        transform-origin: 50% 50%;
        animation: af-pet-idea-ray 1180ms ease-out both;
      }

      .pet-idea-bulb-ray-1 {
        left: 17px;
        top: -5px;
        transform: rotate(90deg) scaleX(.45);
        animation-delay: 80ms;
      }

      .pet-idea-bulb-ray-2 {
        left: -2px;
        top: 9px;
        transform: rotate(142deg) scaleX(.45);
        animation-delay: 150ms;
      }

      .pet-idea-bulb-ray-3 {
        right: -1px;
        top: 10px;
        transform: rotate(38deg) scaleX(.45);
        animation-delay: 220ms;
      }

      .pet-idea-bulb-spark {
        position: absolute;
        width: 5px;
        height: 5px;
        border-radius: 50%;
        background: #222;
        opacity: 0;
        animation: af-pet-idea-spark 1180ms ease-out both;
      }

      .pet-idea-bulb-spark-1 { left: 5px; top: -4px; animation-delay: 210ms; }
      .pet-idea-bulb-spark-2 { left: 36px; top: 1px; animation-delay: 310ms; }
      .pet-idea-bulb-spark-3 { left: 1px; top: 27px; animation-delay: 400ms; }


      .face-emotion-thinking .pet-mouth {
        position: relative;
        display: inline-block;
        overflow: visible;
      }

      .pet-thinking-mouth-anchor {
        opacity: 0;
        pointer-events: none;
      }

      .pet-thinking-wave-mouth {
        position: absolute;
        left: 50%;
        top: 50%;
        width: 12px;
        height: 8px;
        overflow: hidden;
        pointer-events: none;
        transform: translate(-50%, -18%);
      }

      .pet-thinking-wave-mouth svg {
        display: block;
        width: 24px;
        height: 8px;
        animation: af-pet-thinking-wave-flow 680ms linear infinite;
      }

      .pet-thinking-wave-mouth path {
        fill: none;
        stroke: currentColor;
        stroke-width: 1.9;
        stroke-linecap: round;
        stroke-linejoin: round;
      }

      .motion-think-soft {
        animation: af-pet-thinking-soft 1280ms ease-in-out infinite;
      }

      .motion-idea-bulb {
        animation: af-pet-idea-face-pop 520ms cubic-bezier(.18,.85,.25,1.2) both;
      }


      @keyframes af-pet-thinking-wave-flow {
        from { transform: translateX(0); }
        to { transform: translateX(-12px); }
      }

      @keyframes af-pet-thinking-soft {
        0%, 100% { transform: translateY(0) rotate(0deg); }
        50% { transform: translateY(-1px) rotate(-1deg); }
      }

      @keyframes af-pet-idea-face-pop {
        0% { transform: translateY(0) scale(1); }
        35% { transform: translateY(-2px) scale(1.045); }
        72% { transform: translateY(1px) scale(.99); }
        100% { transform: translateY(0) scale(1); }
      }

      @keyframes af-pet-idea-bulb-dance {
        0% { opacity: 0; transform: translate(-5px, 8px) scale(.38) rotate(-22deg); }
        18% { opacity: 1; transform: translate(1px, -2px) scale(1.16) rotate(9deg); }
        32% { opacity: 1; transform: translate(-2px, 1px) scale(.96) rotate(-6deg); }
        48% { opacity: 1; transform: translate(0, -3px) scale(1.04) rotate(4deg); }
        68% { opacity: 1; transform: translate(1px, -1px) scale(1) rotate(-2deg); }
        84% { opacity: 1; transform: translate(0, -4px) scale(.96) rotate(2deg); }
        100% { opacity: 0; transform: translate(2px, -9px) scale(.78) rotate(8deg); }
      }

      @keyframes af-pet-idea-glow {
        0%, 100% { opacity: 0; transform: scale(.55); }
        18%, 72% { opacity: 1; transform: scale(1.12); }
        46% { opacity: .76; transform: scale(.95); }
      }

      @keyframes af-pet-idea-ray {
        0%, 12% { opacity: 0; }
        24% { opacity: .95; }
        48% { opacity: .36; }
        66% { opacity: .9; }
        100% { opacity: 0; }
      }

      @keyframes af-pet-idea-spark {
        0%, 18% { opacity: 0; transform: translate(0, 0) scale(.35); }
        38% { opacity: .88; transform: translate(-1px, -4px) scale(1); }
        72% { opacity: .35; transform: translate(2px, -7px) scale(.72); }
        100% { opacity: 0; transform: translate(4px, -10px) scale(.35); }
      }
    `;

    document.head.appendChild(style);
  }

  function createDom() {
    injectIdeaMotionStyle();

    const root = document.createElement("div");
    root.id = "aflodit-pet-root";
    root.innerHTML = renderTemplate();
    document.body.appendChild(root);

    const quickButtons = Array.from(root.querySelectorAll(".pet-quick-action"));
    const quickButtonMap = quickButtons.reduce((acc, button) => {
      acc[button.dataset.action] = button;
      return acc;
    }, {});

    Object.assign(dom, {
      root,
      pet: root.querySelector("#aflodit-pet"),
      avatar: root.querySelector("#aflodit-pet-avatar"),
      menu: root.querySelector("#aflodit-pet-menu"),
      panel: root.querySelector("#aflodit-pet-panel"),
      help: root.querySelector("#aflodit-pet-help"),
      helpButton: root.querySelector("#aflodit-pet-help-button"),
      mode: root.querySelector("#aflodit-pet-mode"),
      status: root.querySelector("#aflodit-pet-status"),
      contextBlock: root.querySelector("#aflodit-pet-context-block"),
      contextTitle: root.querySelector("#aflodit-pet-context-title"),
      selected: root.querySelector("#aflodit-pet-selected"),
      reply: root.querySelector("#aflodit-pet-reply"),
      refresh: root.querySelector("#aflodit-pet-refresh-action"),
      meta: root.querySelector("#aflodit-pet-meta"),
      ideaBulb: root.querySelector("#aflodit-pet-idea-bulb"),
      face: root.querySelector("#aflodit-pet-face"),
      eyeLeft: root.querySelector("#aflodit-pet-eye-left"),
      mouth: root.querySelector("#aflodit-pet-mouth"),
      eyeRight: root.querySelector("#aflodit-pet-eye-right"),
      faceMark: root.querySelector("#aflodit-pet-face-mark"),
      chatRow: root.querySelector("#aflodit-pet-chat-row"),
      chatInput: root.querySelector("#aflodit-pet-chat-input"),
      chatSend: root.querySelector("#aflodit-pet-chat-send"),
      quickButtons,
      quickButtonMap
    });
  }

  function enforceScrollBoxes() {
    Object.assign(dom.selected.style, {
      maxHeight: "104px",
      overflowY: "auto",
      overflowX: "hidden",
      lineHeight: "1.42",
      padding: "6px 8px"
    });

    Object.assign(dom.reply.style, {
      maxHeight: "148px",
      overflowY: "auto",
      overflowX: "hidden",
      lineHeight: "1.55",
      whiteSpace: "pre-wrap",
      wordBreak: "break-word",
      textOverflow: "clip"
    });
  }

// =========================
  // 6. 文本提取 / 输入解析
  // =========================
  const Extractor = {
    parseChatInput(raw = "") {
      const input = text(raw);
      const useSelection = /(^|\s)@(选区|selection)(?=\s|$)/i.test(input);
      const usePage = /(^|\s)@(页面|page)(?=\s|$)/i.test(input);

      const userText = input
        .replace(/(^|\s)@(选区|selection)(?=\s|$)/ig, " ")
        .replace(/(^|\s)@(页面|page)(?=\s|$)/ig, " ")
        .replace(/\s+/g, " ")
        .trim();

      return { userText, useSelection, usePage };
    },

    parseLocalCommand(raw = "") {
      const input = text(raw);
      if (/^@?(陪读|reading|read)$/i.test(input)) return { type: "enter_reading" };
      if (/^@?(退出陪读|exit_reading|normal)$/i.test(input)) return { type: "exit_reading" };
      return null;
    },

    getSelectedText() {
      return window.getSelection()?.toString().trim() || "";
    },

    updateSelectedText() {
      const selected = this.getSelectedText();
      if (selected) state.selectedText = selected;
      if (actionConfig(state.action).context === "selection") {
        dom.selected.textContent = state.selectedText || "暂无选中文本。";
      }
    },

    getNodeText(node) {
      return String(node?.innerText || node?.textContent || "").trim();
    },

    cleanReadableClone(root) {
      READABLE_SAFE_REMOVE_SELECTORS.forEach((selector) => {
        root.querySelectorAll(selector).forEach((node) => node.remove());
      });
    },

    collectReadableCandidates(root) {
      const nodes = new Set([root]);
      READABLE_SELECTORS.forEach((selector) => {
        root.querySelectorAll(selector).forEach((node) => nodes.add(node));
      });
      return Array.from(nodes).filter((node) => this.getNodeText(node).length >= 200);
    },

    scoreReadableCandidate(node) {
      const rawText = this.getNodeText(node);
      const textLength = rawText.length;
      if (textLength < 200) return -Infinity;

      const linkTextLength = Array.from(node.querySelectorAll("a"))
        .reduce((sum, link) => sum + this.getNodeText(link).length, 0);

      const linkDensity = linkTextLength / Math.max(textLength, 1);
      const paragraphCount = node.querySelectorAll("p").length;
      const headingCount = node.querySelectorAll("h1,h2,h3").length;
      const listItemCount = node.querySelectorAll("li").length;
      const controlCount = node.querySelectorAll("button,input,select,textarea").length;
      const cssSymbolDensity = (rawText.match(/[{};]/g) || []).length / Math.max(textLength, 1);

      const semanticBoost = node.matches?.("article,main,[role='main'],.mw-parser-output,article.markdown-body") ? 8 : 0;
      const textScore = Math.min(textLength / 1000, 10);
      const paragraphScore = Math.min(paragraphCount * 1.8, 14);
      const headingScore = Math.min(headingCount, 4);
      const listScore = Math.min(listItemCount * 0.15, 3);

      return semanticBoost + textScore + paragraphScore + headingScore + listScore
        - linkDensity * 28
        - Math.min(controlCount * 2, 8)
        - cssSymbolDensity * 80;
    },

    pickReadableCandidate(root) {
      return this.collectReadableCandidates(root)
        .map((node) => ({ node, score: this.scoreReadableCandidate(node) }))
        .sort((a, b) => b.score - a.score)[0]?.node || root;
    },

    normalizeReadableText(raw) {
      const seen = new Set();
      return String(raw || "")
        .split(/\n+/)
        .map((line) => line.replace(/\s+/g, " ").trim())
        .filter((line) => line.length >= 2)
        .filter((line) => {
          const key = line.toLowerCase();
          if (seen.has(key)) return false;
          seen.add(key);
          return true;
        })
        .join("\n")
        .trim();
    },

    getPageTextSnippet() {
      if (!document.body) return "";
      const clone = document.body.cloneNode(true);
      this.cleanReadableClone(clone);
      const readableRoot = this.pickReadableCandidate(clone);
      const readableText = this.normalizeReadableText(this.getNodeText(readableRoot));
      return limit(readableText, CONFIG.limits.pageText);
    },

    getPagePreview() {
      const title = limit(document.title || "当前页面", CONFIG.limits.pageTitle);
      const snippet = this.getPageTextSnippet();
      return snippet ? `${title}\n\n${limit(snippet, CONFIG.limits.pagePreview)}` : title;
    }
  };

// =========================
  // 7. 面部 / motion / gaze
  // =========================
  const FaceController = {
    setEmotion(emotion = "neutral") {
      const safeEmotion = FACE_PARTS[emotion] ? emotion : "neutral";
      const parts = FACE_PARTS[safeEmotion];
      dom.eyeLeft.textContent = parts.left;
      dom.eyeRight.textContent = parts.right;
      dom.faceMark.textContent = parts.mark;

      if (safeEmotion === "thinking") {
        // 保留原嘴型字符作为透明占位，确保左右眼间距与原笑脸一致；
        // SVG 波浪线绝对定位在嘴巴原位置，固定可视宽度，只让内部波形流动。
        dom.mouth.innerHTML = `
          <span class="pet-thinking-mouth-anchor">${FACE_PARTS.neutral.mouth}</span>
          <span class="pet-thinking-wave-mouth" aria-hidden="true">
            <svg viewBox="0 0 24 8" preserveAspectRatio="none">
              <path d="M0 4 Q3 1.9 6 4 T12 4 T18 4 T24 4"></path>
            </svg>
          </span>
        `;
      } else {
        dom.mouth.textContent = parts.mouth;
      }

      dom.face.className = `pet-face-core face-emotion-${safeEmotion}`;
    },

    setLookOffset(eyeX = 0, eyeY = 0, mouthX = 0, mouthY = 0) {
      dom.eyeLeft.style.transform = `translate(${eyeX}px, ${eyeY}px)`;
      dom.eyeRight.style.transform = `translate(${eyeX}px, ${eyeY}px)`;
      dom.mouth.style.transform = `translate(${mouthX}px, ${mouthY}px)`;
      dom.faceMark.style.transform = `translate(${mouthX}px, ${mouthY}px)`;
    },

    setLookCenter() {
      this.setLookOffset(0, 0, 0, 0);
    },

    lookAtVector(dx = 0, dy = 0) {
      const eyeX = Math.round(clamp(dx / CONFIG.face.vectorNormX, -1, 1) * CONFIG.face.eyeMoveRange);
      const eyeY = Math.round(clamp(dy / CONFIG.face.vectorNormY, -1, 1) * CONFIG.face.eyeMoveRange);
      const mouthX = Math.round(clamp(dx / CONFIG.face.vectorNormX, -1, 1) * CONFIG.face.mouthMoveRange);
      const mouthY = Math.round(clamp(dy / CONFIG.face.vectorNormY, -1, 1) * CONFIG.face.mouthMoveRange);
      this.setLookOffset(eyeX, eyeY, mouthX, mouthY);
    },

    lookAtPoint(x, y) {
      const center = Geometry.getAvatarCenter();
      this.lookAtVector(x - center.x, y - center.y);
    },

    lookAtElement(element) {
      if (!element || element.classList.contains("hidden")) return this.setLookCenter();
      const rect = element.getBoundingClientRect();
      this.lookAtPoint(rect.left + rect.width / 2, rect.top + rect.height / 2);
    },

    clearMotion() {
      dom.avatar.classList.remove(
        "motion-nod",
        "motion-shake",
        "motion-jump",
        "motion-think",
        "motion-think-soft",
        "motion-idea-bulb"
      );
    },

    playMotion(motion = "idle") {
      this.clearMotion();
      void dom.avatar.offsetWidth;
      const motionClass = {
        nod: "motion-nod",
        shake: "motion-shake",
        jump: "motion-jump",
        think: "motion-think",
        focus: "motion-think-soft"
      }[motion];
      if (motionClass) dom.avatar.classList.add(motionClass);
    },

    clearIdeaTimer() {
      if (state.ideaTimer) window.clearTimeout(state.ideaTimer);
      state.ideaTimer = null;
    },

    hideIdeaBulb({ resetLook = false, clearTimer = true } = {}) {
      if (clearTimer) this.clearIdeaTimer();
      dom.ideaBulb?.classList.add("hidden");
      dom.avatar.classList.remove("motion-idea-bulb");
      if (resetLook) this.setLookCenter();
    },

    startThinkingFace() {
      this.stopLookLoop(true);
      this.stopReplyPeekLoop(true);
      this.hideIdeaBulb({ clearTimer: true });
      this.clearMotion();
      this.setEmotion("thinking");
      // 思考态只动嘴部波浪；眼睛、嘴巴节点位置都回到原笑脸基准位。
      this.setLookCenter();
    },

    playIdeaBulb({ holdMs = CONFIG.face.ideaBulbHoldMs } = {}) {
      this.stopLookLoop(true);
      this.stopReplyPeekLoop(true);
      this.hideIdeaBulb({ clearTimer: true });
      this.clearMotion();
      this.setEmotion("idea");
      // 让脸看向左上方灯泡，嘴巴只轻微跟随，避免脸部整体漂移。
      this.setLookOffset(-4, -4, -1, -1);

      if (dom.ideaBulb) {
        dom.ideaBulb.classList.add("hidden");
        void dom.ideaBulb.offsetWidth;
        dom.ideaBulb.classList.remove("hidden");
      }

      void dom.avatar.offsetWidth;
      dom.avatar.classList.add("motion-idea-bulb");

      state.ideaTimer = window.setTimeout(() => {
        state.ideaTimer = null;
        dom.ideaBulb?.classList.add("hidden");
        dom.avatar.classList.remove("motion-idea-bulb");

        if (state.ui === UI.PANEL) {
          this.setEmotion("happy");
          this.setLookCenter();
          if (!state.running) this.startReplyPeekLoop();
        }
      }, holdMs);
    },

    stopLookLoop(reset = true) {
      if (state.lookTimer) window.clearTimeout(state.lookTimer);
      state.lookTimer = null;
      if (reset) this.setLookCenter();
    },

    stopReplyPeekLoop(reset = true) {
      if (state.replyPeekTimer) window.clearTimeout(state.replyPeekTimer);
      state.replyPeekTimer = null;
      if (reset) this.setLookCenter();
    },

    stopReadingLoop(reset = true) {
      if (state.readingTimer) window.clearTimeout(state.readingTimer);
      state.readingTimer = null;
      state.lastMouseAt = 0;
      if (reset) this.setLookCenter();
    },

    startMenuLookLoop() {
      this.stopLookLoop(false);
      this.hideIdeaBulb({ clearTimer: true });
      this.setEmotion("neutral");

      const tick = () => {
        if (state.ui !== UI.MENU || dom.menu.classList.contains("hidden")) return;
        const visibleTargets = dom.quickButtons.filter((btn) => !btn.classList.contains("hidden"));
        const target = visibleTargets[Math.floor(Math.random() * visibleTargets.length)];
        this.lookAtElement(target);
        state.lookTimer = window.setTimeout(tick, randomBetween(CONFIG.face.menuLookDelay.min, CONFIG.face.menuLookDelay.max));
      };

      tick();
    },

    startReplyPeekLoop() {
      this.stopReplyPeekLoop(false);
      state.replyPeekTimer = window.setTimeout(() => {
        const tick = () => {
          if (state.ui !== UI.PANEL || state.running) return;

          this.setEmotion("happy");
          this.lookAtElement(dom.reply || dom.panel);

          state.replyPeekTimer = window.setTimeout(() => {
            if (state.ui !== UI.PANEL || state.running) return;
            this.setEmotion("happy");
            this.setLookCenter();
            state.replyPeekTimer = window.setTimeout(tick, randomBetween(CONFIG.face.replyPeekGapMs.min, CONFIG.face.replyPeekGapMs.max));
          }, randomBetween(CONFIG.face.replyPeekHoldMs.min, CONFIG.face.replyPeekHoldMs.max));
        };

        tick();
      }, CONFIG.face.replyPeekStartMs);
    },

    startReadingLoop() {
      this.stopReadingLoop(false);

      const tick = () => {
        if (state.mode !== MODE.READING) return;

        const mouseRecentlyActive = Date.now() - state.lastMouseAt < CONFIG.reading.mouseHoldMs;
        if (!mouseRecentlyActive) {
          setActivity(ACTIVITY.OBSERVING);
          this.setEmotion(Math.random() < 0.25 ? "happy" : "neutral");

          const choices = [dom.panel, dom.menu, dom.reply, dom.help].filter((el) => el && !el.classList.contains("hidden"));
          const target = choices[Math.floor(Math.random() * choices.length)] || dom.avatar;
          if (target === dom.avatar) this.setLookCenter();
          else this.lookAtElement(target);
        }

        state.readingTimer = window.setTimeout(tick, randomBetween(CONFIG.reading.glanceDelay.min, CONFIG.reading.glanceDelay.max));
      };

      tick();
    },

    reactFace({ emotion = "neutral", motion = "idle" } = {}) {
      this.hideIdeaBulb({ clearTimer: true });
      this.stopLookLoop(true);
      this.stopReplyPeekLoop(true);
      this.setEmotion(emotion);
      this.playMotion(motion);
    },

    resetFace() {
      this.hideIdeaBulb({ clearTimer: true });
      this.stopLookLoop(true);
      this.stopReplyPeekLoop(true);
      this.clearMotion();
      this.setEmotion("neutral");
      this.setLookCenter();
    },

    handleReadingMouseMove(event) {
      if (state.mode !== MODE.READING || !dom.avatar) return;
      const center = Geometry.getAvatarCenter();
      const dx = event.clientX - center.x;
      const dy = event.clientY - center.y;
      const distance = Math.hypot(dx, dy);
      if (distance > CONFIG.reading.mouseRange) return;

      state.lastMouseAt = Date.now();
      setActivity(ACTIVITY.TRACKING_MOUSE);
      this.setEmotion("happy");
      this.lookAtVector(dx, dy);
    }
  };

// =========================
  // 4. 几何 / 布局工具
  // =========================
  const Geometry = {
    getViewport() {
      return {
        width: Math.max(document.documentElement.clientWidth || 0, window.innerWidth || 0),
        height: Math.max(document.documentElement.clientHeight || 0, window.innerHeight || 0)
      };
    },

    getAvatarSize() {
      const rect = dom.avatar?.getBoundingClientRect?.();
      const fallback = CONFIG.drag.avatarSize;
      return { width: rect?.width || fallback, height: rect?.height || fallback };
    },

    getAvatarRect() {
      return dom.avatar?.getBoundingClientRect?.() || dom.root?.getBoundingClientRect?.();
    },

    getAvatarCenter() {
      const rect = this.getAvatarRect();
      return {
        x: rect.left + rect.width / 2,
        y: rect.top + rect.height / 2
      };
    },

    clampPosition(position = state.position) {
      const viewport = this.getViewport();
      const size = this.getAvatarSize();
      const margin = CONFIG.drag.viewportMargin;
      const maxX = Math.max(margin, viewport.width - size.width - margin);
      const maxY = Math.max(margin, viewport.height - size.height - margin);

      return {
        x: Math.round(clamp(Number(position.x) || 0, margin, maxX)),
        y: Math.round(clamp(Number(position.y) || 0, margin, maxY)),
        snapEdge: position.snapEdge || "free"
      };
    },

    snapPosition(position = state.position) {
      const viewport = this.getViewport();
      const size = this.getAvatarSize();
      const margin = CONFIG.drag.viewportMargin;
      const bounds = {
        left: margin,
        top: margin,
        right: Math.max(margin, viewport.width - size.width - margin),
        bottom: Math.max(margin, viewport.height - size.height - margin)
      };
      const current = this.clampPosition(position);
      const candidates = [
        { edge: "left", distance: Math.abs(current.x - bounds.left), x: bounds.left, y: current.y },
        { edge: "right", distance: Math.abs(current.x - bounds.right), x: bounds.right, y: current.y },
        { edge: "top", distance: Math.abs(current.y - bounds.top), x: current.x, y: bounds.top },
        { edge: "bottom", distance: Math.abs(current.y - bounds.bottom), x: current.x, y: bounds.bottom }
      ].sort((a, b) => a.distance - b.distance);

      const nearest = candidates[0];
      if (nearest.distance <= CONFIG.drag.snapDistance) {
        return this.clampPosition({ x: nearest.x, y: nearest.y, snapEdge: nearest.edge });
      }

      return { ...current, snapEdge: "free" };
    },

    clampFloating(left, top, width, height) {
      const viewport = this.getViewport();
      const margin = CONFIG.drag.viewportMargin;
      const maxLeft = Math.max(margin, viewport.width - width - margin);
      const maxTop = Math.max(margin, viewport.height - height - margin);
      return {
        left: clamp(left, margin, maxLeft),
        top: clamp(top, margin, maxTop)
      };
    },

    setAbsolutePosition(element, left, top) {
      const rootRect = dom.root.getBoundingClientRect();
      element.style.left = `${Math.round(left - rootRect.left)}px`;
      element.style.top = `${Math.round(top - rootRect.top)}px`;
      element.style.right = "auto";
      element.style.bottom = "auto";
    },

    getFloatingSize(element, fallbackWidth, fallbackHeight) {
      return {
        width: element.offsetWidth || fallbackWidth,
        height: element.offsetHeight || fallbackHeight
      };
    },

    rectsOverlap(a, b, margin = 0) {
      return !(
        a.right + margin <= b.left ||
        a.left >= b.right + margin ||
        a.bottom + margin <= b.top ||
        a.top >= b.bottom + margin
      );
    },

    expandRect(rect, padding = 0) {
      return {
        left: rect.left - padding,
        top: rect.top - padding,
        right: rect.right + padding,
        bottom: rect.bottom + padding,
        width: rect.width + padding * 2,
        height: rect.height + padding * 2
      };
    }
  };
// =========================
  // 8. 浮层布局系统
  // =========================
  const LayoutManager = {
    setRootPosition(position, { snap = false } = {}) {
      const next = snap ? Geometry.snapPosition(position) : Geometry.clampPosition(position);
      state.position = next;

      dom.root.style.left = `${next.x}px`;
      dom.root.style.top = `${next.y}px`;
      dom.root.style.right = "auto";
      dom.root.style.bottom = "auto";
      dom.root.dataset.snapEdge = next.snapEdge || "free";

      this.updateFloatingLayout();
    },

    setInitialPosition() {
      const viewport = Geometry.getViewport();
      const size = Geometry.getAvatarSize();
      const offset = CONFIG.drag.initialOffset;
      this.setRootPosition({
        x: viewport.width - size.width - offset,
        y: viewport.height - size.height - offset,
        snapEdge: "right"
      }, { snap: false });
    },

    handleViewportResize() {
      this.setRootPosition(state.position, { snap: state.position.snapEdge !== "free" });
      this.updateFloatingLayout();
    },

    getOpenOrientation() {
      const viewport = Geometry.getViewport();
      const avatarCenter = Geometry.getAvatarCenter();
      const openHorizontal = avatarCenter.x > viewport.width / 2 ? "left" : "right";
      const openVertical = avatarCenter.y > viewport.height / 2 ? "up" : "down";
      const signX = openHorizontal === "left" ? -1 : 1;
      const signY = openVertical === "up" ? -1 : 1;

      return {
        openHorizontal,
        openVertical,
        signX,
        signY,
        menuVariant: `${openVertical === "up" ? "b" : "t"}${openHorizontal === "left" ? "r" : "l"}`
      };
    },

    getMenuButtonPositions(orientation) {
      const avatarCenter = Geometry.getAvatarCenter();
      const buttonWidth = 100;
      const buttonHeight = 40;

      return MENU_BUTTON_OFFSETS.map((item) => {
        const dx = Math.abs(item.dx) * orientation.signX;
        // MENU_BUTTON_OFFSETS 的 dy 以“向上展开”为基准；在上方区域时做上下镜像。
        const dy = item.dy * (orientation.signY === -1 ? 1 : -1);
        const desiredLeft = avatarCenter.x + dx - buttonWidth / 2;
        const desiredTop = avatarCenter.y + dy - buttonHeight / 2;
        const clamped = Geometry.clampFloating(desiredLeft, desiredTop, buttonWidth, buttonHeight);
        return { key: item.key, ...clamped };
      });
    },

    applyMenuButtonLayout(button, left, top) {
      const rootRect = dom.root.getBoundingClientRect();
      button.style.left = `${Math.round(left - rootRect.left)}px`;
      button.style.top = `${Math.round(top - rootRect.top)}px`;
      button.style.right = "auto";
      button.style.bottom = "auto";
    },

    applyMenuTailDirection(button) {
      const buttonRect = button.getBoundingClientRect();
      const avatarRect = Geometry.getAvatarRect();
      const buttonCenterX = buttonRect.left + buttonRect.width / 2;
      const buttonCenterY = buttonRect.top + buttonRect.height / 2;
      const avatarCenterX = avatarRect.left + avatarRect.width / 2;
      const avatarCenterY = avatarRect.top + avatarRect.height / 2;
      const dx = avatarCenterX - buttonCenterX;
      const dy = avatarCenterY - buttonCenterY;

      button.classList.remove("tail-top", "tail-bottom", "tail-left", "tail-right");
      if (Math.abs(dx) > Math.abs(dy)) {
        button.classList.add(dx > 0 ? "tail-right" : "tail-left");
      } else {
        button.classList.add(dy > 0 ? "tail-bottom" : "tail-top");
      }
    },

    updateMenuLayout() {
      if (!dom.menu || dom.menu.classList.contains("hidden")) return;

      const rootRect = dom.root.getBoundingClientRect();
      const orientation = this.getOpenOrientation();
      state.layout.menuVariant = orientation.menuVariant;
      dom.menu.dataset.variant = orientation.menuVariant;

      // 菜单容器只作为按钮承载层，直接锚在 root 上；按钮按真实屏幕坐标计算。
      Geometry.setAbsolutePosition(dom.menu, rootRect.left, rootRect.top);

      this.getMenuButtonPositions(orientation).forEach((item) => {
        const button = dom.quickButtonMap[item.key];
        if (!button) return;
        this.applyMenuButtonLayout(button, item.left, item.top);
      });

      window.requestAnimationFrame(() => {
        dom.quickButtons.forEach((button) => this.applyMenuTailDirection(button));
      });
    },

    updatePanelLayout() {
      if (!dom.panel || dom.panel.classList.contains("hidden")) return;

      const size = Geometry.getFloatingSize(dom.panel, CONFIG.drag.floatingWidth, 260);
      const viewport = Geometry.getViewport();
      const avatarRect = Geometry.getAvatarRect();
      const margin = CONFIG.drag.viewportMargin;
      const gap = CONFIG.drag.panelGap;

      const roomAbove = avatarRect.top - margin;
      const roomBelow = viewport.height - avatarRect.bottom - margin;
      const roomLeft = avatarRect.left - margin;
      const roomRight = viewport.width - avatarRect.right - margin;

      const preferVertical = Math.max(roomAbove, roomBelow) >= size.height + gap || Math.min(roomLeft, roomRight) < size.width * 0.4;
      let desiredLeft = avatarRect.left;
      let desiredTop = avatarRect.bottom + gap;

      if (preferVertical) {
        const placeAbove = roomAbove >= size.height + gap || roomAbove >= roomBelow;
        state.layout.panelPlacement = placeAbove ? "top" : "bottom";
        desiredTop = placeAbove ? avatarRect.top - size.height - gap : avatarRect.bottom + gap;
        desiredLeft = (avatarRect.left + avatarRect.right) / 2 > viewport.width / 2
          ? avatarRect.right - size.width
          : avatarRect.left;
      } else {
        const placeLeft = roomLeft >= size.width + gap || roomLeft >= roomRight;
        state.layout.panelPlacement = placeLeft ? "left" : "right";
        desiredLeft = placeLeft ? avatarRect.left - size.width - gap : avatarRect.right + gap;
        desiredTop = avatarRect.top;
      }

      const next = Geometry.clampFloating(desiredLeft, desiredTop, size.width, size.height);
      Geometry.setAbsolutePosition(dom.panel, next.left, next.top);
    },

    getHelpCandidates(size, anchorRect, avatarRect) {
      const gap = CONFIG.drag.helpGap;
      return [
        { name: "above", left: anchorRect.left, top: anchorRect.top - size.height - gap },
        { name: "below", left: anchorRect.left, top: anchorRect.bottom + gap },
        { name: "right", left: anchorRect.right + gap, top: anchorRect.top },
        { name: "left", left: anchorRect.left - size.width - gap, top: anchorRect.top }
      ].map((item) => {
        const clamped = Geometry.clampFloating(item.left, item.top, size.width, size.height);
        const rect = {
          left: clamped.left,
          top: clamped.top,
          right: clamped.left + size.width,
          bottom: clamped.top + size.height,
          width: size.width,
          height: size.height
        };
        const overlapAvatar = Geometry.rectsOverlap(rect, Geometry.expandRect(avatarRect, 10));
        return { ...item, ...clamped, rect, overlapAvatar };
      });
    },

    updateHelpLayout() {
      if (!dom.help || dom.help.classList.contains("hidden")) return;

      const size = Geometry.getFloatingSize(dom.help, CONFIG.drag.floatingWidth, CONFIG.drag.helpHeight);
      const panelVisible = dom.panel && !dom.panel.classList.contains("hidden");
      const avatarRect = Geometry.getAvatarRect();
      const anchorRect = panelVisible ? dom.panel.getBoundingClientRect() : avatarRect;
      const candidates = this.getHelpCandidates(size, anchorRect, avatarRect);

      let ordered = candidates;

      if (panelVisible) {
        // help 要和 panel 站在同一侧，更远离 avatar，避免被笑脸切到。
        const ax = (avatarRect.left + avatarRect.right) / 2;
        const ay = (avatarRect.top + avatarRect.bottom) / 2;
        const px = (anchorRect.left + anchorRect.right) / 2;
        const py = (anchorRect.top + anchorRect.bottom) / 2;

        const preferred = Math.abs(px - ax) > Math.abs(py - ay)
          ? (px >= ax ? ["right", "above", "below", "left"] : ["left", "above", "below", "right"])
          : (py >= ay ? ["below", "right", "left", "above"] : ["above", "right", "left", "below"]);

        ordered = preferred.flatMap((name) => candidates.filter((item) => item.name === name));
      }

      const best = ordered.find((item) => !item.overlapAvatar) || ordered[0];
      Geometry.setAbsolutePosition(dom.help, best.left, best.top);
    },

    updateFloatingLayout() {
      if (!dom.root) return;
      this.updateMenuLayout();
      this.updatePanelLayout();
      this.updateHelpLayout();
    }
  };

// =========================
  // 11. 后端链路
  // =========================
  const ActionRunner = {
    validate(action, userText = "") {
      const config = actionConfig(action);
      Extractor.updateSelectedText();

      if (action === ACTION.CHAT) {
        const chat = Extractor.parseChatInput(userText);
        if (!chat.userText) return config.empty;
        if (chat.useSelection && !(state.selectedText || Extractor.getSelectedText())) {
          return "请先选中文本，或去掉 @选区。";
        }
        return "";
      }

      if (config.needsSelection && !state.selectedText) return config.empty;
      if (config.needsUserText && !userText.trim()) return config.empty;
      if (action === ACTION.SUMMARY && !Extractor.getPageTextSnippet()) return config.empty;
      return "";
    },

    buildPayload(action, userText = "") {
      const config = actionConfig(action);
      const selectedText = state.selectedText || Extractor.getSelectedText();
      const chat = action === ACTION.CHAT ? Extractor.parseChatInput(userText) : null;
      const finalUserText = chat ? chat.userText : userText;
      const useSelection = chat ? chat.useSelection : action !== ACTION.CHAT;
      const usePage = chat ? chat.usePage : config.sendsPageText;
      const hasContext = useSelection || usePage;

      return {
        action: limit(action, CONFIG.limits.action),
        user_text: limit(finalUserText, CONFIG.limits.userText),
        selected_text: useSelection ? limit(selectedText, CONFIG.limits.selectedText) : "",
        page_title: hasContext ? limit(document.title, CONFIG.limits.pageTitle) : "",
        page_url: hasContext ? limit(window.location.href, CONFIG.limits.pageUrl) : "",
        page_text_snippet: usePage ? Extractor.getPageTextSnippet() : "",
        character_state: limit("thinking", CONFIG.limits.characterState)
      };
    },

    async callBackend(payload) {
      const response = await fetch(CONFIG.backendUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-Aflodit-Pet-Token": CONFIG.localClientToken
        },
        body: JSON.stringify(payload)
      });

      const data = await response.json().catch(() => null);
      if (!response.ok) throw new Error(data?.reply || `后端请求失败：${response.status}`);
      return data;
    },

    handleStreamEventLine(line, handlers) {
      if (!line.trim()) return null;
      const event = JSON.parse(line);

      if (event.type === "delta") {
        handlers.onDelta?.(String(event.text || ""));
        return null;
      }

      if (event.type === "final") {
        return event.data || null;
      }

      if (event.type === "error") {
        return event.data || null;
      }

      return null;
    },

    async callStreamingBackend(payload, handlers = {}) {
      const response = await fetch(CONFIG.streamUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-Aflodit-Pet-Token": CONFIG.localClientToken
        },
        body: JSON.stringify(payload)
      });

      if (!response.ok || !response.body) {
        throw new Error(`流式后端请求失败：${response.status}`);
      }

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = "";
      let finalData = null;

      while (true) {
        const { value, done } = await reader.read();
        buffer += decoder.decode(value || new Uint8Array(), { stream: !done });
        const lines = buffer.split(/\r?\n/);
        buffer = lines.pop() || "";

        for (const line of lines) {
          const result = this.handleStreamEventLine(line, handlers);
          if (result) finalData = result;
        }

        if (done) break;
      }

      if (buffer.trim()) {
        const result = this.handleStreamEventLine(buffer, handlers);
        if (result) finalData = result;
      }

      if (!finalData) throw new Error("流式后端没有返回 final 事件。");
      return finalData;
    },

    async runAction(action, userText = "") {
      if (state.running) return;

      UIController.openPanel(action);
      const validationError = this.validate(action, userText);
      if (validationError) {
        UIController.showWarning(validationError);
        return;
      }

      const requestId = ++state.requestId;
      const payload = this.buildPayload(action, userText.trim());
      UIController.showLoading(action);
      setRunning(true);

      try {
        log("request", payload);
        let result;
        if (CONFIG.streamEnabled) {
          try {
            UIController.showStreamingStart(action);
            result = await this.callStreamingBackend(payload, {
              onDelta(delta) {
                if (requestId === state.requestId && state.ui === UI.PANEL) {
                  UIController.appendStreamingDelta(delta);
                }
              }
            });
          } catch (streamError) {
            log("stream fallback", streamError);
            if (requestId !== state.requestId || state.ui !== UI.PANEL) return;
            UIController.showLoading(action);
            result = await this.callBackend(payload);
          }
        } else {
          result = await this.callBackend(payload);
        }
        if (requestId !== state.requestId || state.ui !== UI.PANEL) return;
        log("response", result);
        UIController.showResult(result);
      } catch (error) {
        if (requestId !== state.requestId || state.ui !== UI.PANEL) return;
        console.error(error);
        UIController.showError(error);
      } finally {
        if (requestId === state.requestId) setRunning(false);
      }
    }
  };

// =========================
  // 10. UI 控制
  // =========================
  const UIController = {
    closeMenu(resetLook = true) {
      dom.menu.classList.add("hidden");
      FaceController.stopLookLoop(resetLook);
    },

    openMenu() {
      FaceController.stopReplyPeekLoop(true);
      Extractor.updateSelectedText();
      this.closePanel();
      dom.menu.classList.remove("hidden");
      state.ui = UI.MENU;
      LayoutManager.updateFloatingLayout();
      FaceController.startMenuLookLoop();
    },

    closePanel() {
      dom.panel.classList.add("hidden");
      dom.refresh.classList.add("hidden");
      dom.help.classList.add("hidden");
    },

    toggleHelp() {
      const willOpen = dom.help.classList.contains("hidden");
      if (willOpen) {
        dom.help.style.visibility = "hidden";
        dom.help.classList.remove("hidden");
        LayoutManager.updateFloatingLayout();
        window.requestAnimationFrame(() => { dom.help.style.visibility = ""; });
        return;
      }
      dom.help.classList.add("hidden");
    },

    openPanel(action) {
      const config = actionConfig(action);
      state.action = action;
      Extractor.updateSelectedText();
      this.closeMenu(true);
      enforceScrollBoxes();

      state.ui = UI.PANEL;
      dom.panel.classList.remove("hidden");
      dom.help.classList.add("hidden");
      dom.mode.textContent = config.label;
      dom.status.textContent = config.idle;
      dom.reply.textContent = "暂无回复。";
      dom.reply.scrollTop = 0;
      dom.refresh.classList.toggle("hidden", !config.refreshable);
      setBubbleType("normal");
      setMeta("neutral", "idle");

      dom.chatRow.classList.toggle("hidden", !config.needsUserText);
      dom.contextBlock.classList.toggle("hidden", config.context === "none");

      if (config.needsUserText) {
        window.setTimeout(() => dom.chatInput.focus(), 0);
      } else if (config.context === "page") {
        dom.contextTitle.textContent = config.contextTitle;
        dom.selected.textContent = Extractor.getPagePreview() || "当前无法读取页面内容。";
      } else if (config.context === "selection") {
        dom.contextTitle.textContent = config.contextTitle;
        dom.selected.textContent = state.selectedText || "暂无选中文本。";
      }

      LayoutManager.updateFloatingLayout();
    },

    showWarning(message) {
      FaceController.stopReplyPeekLoop(true);
      this.closeMenu(false);
      dom.panel.classList.remove("hidden");
      state.ui = UI.PANEL;
      dom.status.textContent = "无法执行当前动作。";
      dom.reply.textContent = message;
      dom.reply.scrollTop = 0;
      setMeta("confused", "shake");
      setBubbleType("warning");
      LayoutManager.updateFloatingLayout();
      FaceController.reactFace({ emotion: "confused", motion: "shake" });
    },

    showLoading(action) {
      FaceController.stopReplyPeekLoop(true);
      const config = actionConfig(action);
      dom.status.textContent = config.loading;
      dom.reply.textContent = "思考中...";
      delete dom.reply.dataset.streaming;
      dom.reply.scrollTop = 0;
      setMeta("thinking", "focus");
      setBubbleType("info");
      LayoutManager.updateFloatingLayout();
      FaceController.startThinkingFace();
    },

    showStreamingStart(action) {
      this.showLoading(action);
      dom.status.textContent = "正在接收流式回复...";
      dom.reply.textContent = "";
      dom.reply.dataset.streaming = "true";
      setMeta("thinking", "think");
    },

    appendStreamingDelta(delta = "") {
      if (!delta) return;
      if (dom.reply.dataset.streaming !== "true") {
        dom.reply.textContent = "";
        dom.reply.dataset.streaming = "true";
      }
      dom.reply.textContent += delta;
      dom.reply.scrollTop = dom.reply.scrollHeight;
      LayoutManager.updateFloatingLayout();
    },

    resolveFinalFace(result = {}) {
      const bubbleType = result.bubble_type || "normal";
      if (bubbleType === "error" || result.emotion === "error") return { emotion: "error", motion: "shake" };
      if (bubbleType === "warning" || result.emotion === "confused") return { emotion: "confused", motion: "shake" };
      return { emotion: "idea", motion: "bulb" };
    },

    showResult(result = {}) {
      const finalFace = this.resolveFinalFace(result);
      enforceScrollBoxes();
      dom.status.textContent = "本地后端已返回结果。";
      dom.reply.textContent = result.reply || "后端没有返回 reply。";
      delete dom.reply.dataset.streaming;
      dom.reply.scrollTop = 0;
      setMeta(finalFace.emotion, finalFace.motion);
      setBubbleType(result.bubble_type || "normal");
      LayoutManager.updateFloatingLayout();
      if (finalFace.motion === "bulb") {
        FaceController.playIdeaBulb();
      } else {
        FaceController.reactFace(finalFace);
        if (finalFace.emotion === "happy") FaceController.startReplyPeekLoop();
      }
    },

    showError(error) {
      FaceController.stopReplyPeekLoop(true);
      dom.status.textContent = "请求本地后端失败。";
      dom.reply.textContent = String(error?.message || error);
      delete dom.reply.dataset.streaming;
      dom.reply.scrollTop = 0;
      setMeta("error", "shake");
      setBubbleType("error");
      LayoutManager.updateFloatingLayout();
      FaceController.reactFace({ emotion: "error", motion: "shake" });
    },

    closeAll() {
      state.requestId += 1;
      FaceController.stopReadingLoop(true);
      setMode(MODE.NORMAL);
      setActivity(ACTIVITY.IDLE);
      dom.avatar.title = "AFlodit Pet Copilot";
      this.closeMenu(false);
      this.closePanel();
      state.ui = UI.IDLE;
      state.action = ACTION.CHAT;
      setRunning(false);
      setBubbleType("normal");
      FaceController.resetFace();
    },

    enterReadingMode() {
      state.requestId += 1;
      setRunning(false);
      this.closeMenu(false);
      this.closePanel();
      FaceController.stopLookLoop(false);
      FaceController.stopReplyPeekLoop(false);
      FaceController.hideIdeaBulb({ clearTimer: true });
      FaceController.clearMotion();

      state.ui = UI.IDLE;
      state.action = ACTION.CHAT;
      setMode(MODE.READING);
      setActivity(ACTIVITY.OBSERVING);

      dom.avatar.title = "陪读模式中：点击退出并返回 Chat";
      FaceController.setEmotion("happy");
      FaceController.setLookCenter();
      FaceController.startReadingLoop();
    },

    exitReadingMode({ openChat = true } = {}) {
      if (state.mode !== MODE.READING) {
        if (openChat) this.openPanel(ACTION.CHAT);
        return;
      }

      state.requestId += 1;
      FaceController.stopReadingLoop(true);
      setMode(MODE.NORMAL);
      setActivity(ACTIVITY.IDLE);
      dom.avatar.title = "AFlodit Pet Copilot";
      FaceController.resetFace();
      if (openChat) this.openPanel(ACTION.CHAT);
    }
  };
// =========================
  // 12. 拖拽
  // =========================
  const DragManager = {
    begin(event) {
      if (event.button !== undefined && event.button !== 0) return;

      const position = Geometry.clampPosition(state.position);
      Object.assign(state.drag, {
        active: true,
        pointerId: event.pointerId,
        startX: event.clientX,
        startY: event.clientY,
        originX: position.x,
        originY: position.y,
        moved: false
      });

      dom.root.classList.add("pet-dragging");
      dom.avatar.setPointerCapture?.(event.pointerId);
      event.preventDefault();
      event.stopPropagation();
    },

    move(event) {
      if (!state.drag.active || event.pointerId !== state.drag.pointerId) return;
      const dx = event.clientX - state.drag.startX;
      const dy = event.clientY - state.drag.startY;
      const distance = Math.hypot(dx, dy);
      if (!state.drag.moved && distance < CONFIG.drag.dragThreshold) return;

      state.drag.moved = true;
      LayoutManager.setRootPosition({
        x: state.drag.originX + dx,
        y: state.drag.originY + dy,
        snapEdge: "free"
      }, { snap: false });

      event.preventDefault();
    },

    end(event) {
      if (!state.drag.active || event.pointerId !== state.drag.pointerId) return;

      const didMove = state.drag.moved;
      state.drag.active = false;
      state.drag.pointerId = null;
      dom.root.classList.remove("pet-dragging");
      dom.avatar.releasePointerCapture?.(event.pointerId);

      if (didMove) {
        LayoutManager.setRootPosition(state.position, { snap: true });
        state.drag.suppressClick = true;
        window.setTimeout(() => { state.drag.suppressClick = false; }, 160);
      }
    }
  };
// =========================
  // 13. 事件绑定
  // =========================
  function bindEvents() {
    on(document, "selectionchange", () => Extractor.updateSelectedText());
    on(document, "mousemove", (event) => FaceController.handleReadingMouseMove(event), { passive: true });
    on(window, "resize", () => LayoutManager.handleViewportResize());

    on(dom.avatar, "pointerdown", (event) => DragManager.begin(event));
    on(dom.avatar, "pointermove", (event) => DragManager.move(event));
    on(dom.avatar, "pointerup", (event) => DragManager.end(event));
    on(dom.avatar, "pointercancel", (event) => DragManager.end(event));

    on(dom.avatar, "click", (event) => {
      event.stopPropagation();

      if (state.drag.suppressClick) {
        event.preventDefault();
        state.drag.suppressClick = false;
        return;
      }

      if (state.mode === MODE.READING) {
        UIController.exitReadingMode({ openChat: true });
        return;
      }

      if (state.ui === UI.IDLE) return UIController.openMenu();
      if (state.ui === UI.MENU) return UIController.openPanel(ACTION.CHAT);
      UIController.closeAll();
    });

    on(dom.menu, "click", (event) => event.stopPropagation());
    on(dom.panel, "click", (event) => event.stopPropagation());
    on(dom.help, "click", (event) => event.stopPropagation());

    on(dom.helpButton, "click", (event) => {
      event.stopPropagation();
      UIController.toggleHelp();
    });

    dom.quickButtons.forEach((button) => {
      on(button, "click", (event) => {
        event.stopPropagation();
        ActionRunner.runAction(button.dataset.action);
      });
    });

    on(dom.refresh, "click", (event) => {
      event.stopPropagation();
      if (actionConfig(state.action).refreshable) ActionRunner.runAction(state.action);
    });

    on(dom.chatSend, "click", () => {
      const value = dom.chatInput.value;
      const localCommand = Extractor.parseLocalCommand(value);
      dom.chatInput.value = "";

      if (localCommand?.type === "enter_reading") return UIController.enterReadingMode();
      if (localCommand?.type === "exit_reading") return UIController.exitReadingMode({ openChat: true });
      ActionRunner.runAction(ACTION.CHAT, value);
    });

    on(dom.chatInput, "keydown", (event) => {
      if (event.key === "Enter" && !event.shiftKey) {
        event.preventDefault();
        dom.chatSend.click();
      }
    });

    on(document, "click", (event) => {
      if (state.ui === UI.MENU && !dom.pet?.contains(event.target)) UIController.closeAll();
    });

    on(document, "keydown", (event) => {
      if (event.key === "Escape" && state.ui !== UI.IDLE) UIController.closeAll();
    });
  }
// =========================
  // 14. 生命周期
  // =========================
  function destroy() {
    state.requestId += 1;
    cleanups.splice(0).forEach((cleanup) => cleanup());
    FaceController.stopLookLoop(true);
    FaceController.stopReplyPeekLoop(true);
    FaceController.stopReadingLoop(true);
    FaceController.hideIdeaBulb({ clearTimer: true });
    dom.root?.remove();
    state.ui = UI.IDLE;
    state.mode = MODE.NORMAL;
    state.activity = ACTIVITY.IDLE;
    state.running = false;
  }

  function init() {
    createDom();
    LayoutManager.setInitialPosition();
    setMode(MODE.NORMAL);
    setActivity(ACTIVITY.IDLE);
    enforceScrollBoxes();
    FaceController.resetFace();
    bindEvents();
    window[GLOBAL_KEY] = { version: CONFIG.version, destroy };
  }

  init();
})();
